import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
import "./globals.css";
import TopMenu from "./component/topmenu";
import Footer from "./component/footer";

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Nofeh Code Studio",
  description: "Generated by Amir Berenji",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TopMenu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
